### ISSUE TITLE
What is latest version? In GitHub or ieee?

### ISSUE THREAD

**Issue by stain** [biocompute-objects/BCO_Documentation#114]
I see https://github.com/biocompute-objects/BCO_Specification/releases/tag/22.01 of a release 22.01 from 2022.  This is confusing as the README says:

> Current Release - IEEE-2791-2020
> For developers and advanced users, the BCO specification id derived from [IEEE-2791-2020](https://opensource.ieee.org/2791-object/ieee-2791-schema) provides authoritative documentation on the construction of BioCompute Objects using [JSON schema](https://json-schema.org/).

So is the latest version BCO 22.01 from GitHub or https://w3id.org/ieee/ieee-2791-schema/ from IEEE GitLab (tagged [version-1.4](https://opensource.ieee.org/2791-object/ieee-2791-schema/-/tags/version-1.4))?

**Comment by kee007ney** [comment]
@stain Sorry, not sure why it took so long for this comment to be addressed; if I understand your question correctly, "BCO_Specification" is a bit of a misnomer for this repo. At this point, it's just hosting website related content. The IEEE repository is the definitive source for the schema. @HadleyKing I wonder how much of a pain it would be to rename this if it's causing confusion?

**Comment by HadleyKing** [comment]
Renaming a repo will break any links to that content. But this is exactly the situation we started using the `w3id.org` space for. I can set up a redirect there, rename the repo and then someone can update the  README.md here.
