### ISSUE TITLE
set up a redirect at w3id for this repos current semantic URL

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/BCO_Documentation#117]
1. Read the instructions at https://github.com/biocompute-objects/w3id.org/tree/master?tab=readme-ov-file#permanent-identifiers-for-the-web
2. Modify the files at https://github.com/biocompute-objects/w3id.org/tree/master/biocompute to redirect from `https://github.com/biocompute-objects/BCO_Specification` to `https://github.com/biocompute-objects/BCO_Documentation`
3. Submit a PR to the upstream branch and wait for approval and merge. 
4. test and document

**Comment by tiwa1154** [comment]
Submitted PR: https://github.com/perma-id/w3id.org/pull/3939
